# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
# I want to create some variables for my pipeline
  imageRepo: sampleRepo
  tag: '$(Build.BuildId)'

# I choose Docker to build but would edit the edit by clicking on settings to perform build and push
# after the build and push stage, the nex will be to deploy it to AKS
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
#      vmImage: ubuntu-latest
      name: Self-hosted-AgentPool
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ACR'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifest'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: deploy to dev
  dependsOn: Build
  variables:
    acrsecret: k8sexamplesacrauth
  jobs:
  - deployment: Deploy
    displayName: deploy to AKS
    environment: 'K8sDev.default'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifest'
              targetPath: '$(Pipeline.Workspace)/manifest'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acrsecret)'
              dockerRegistryEndpoint: 'ACR'
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifest/deployment.yml
                $(Pipeline.Workspace)/manifest/service.yml

